# Generated by Django 4.2.3 on 2023-09-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('brand', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('features', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('colors', models.CharField(max_length=10)),
                ('sizes', models.CharField(max_length=10)),
                ('availability', models.BooleanField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('num_reviews', models.IntegerField()),
                ('seller_name', models.CharField(max_length=50)),
                ('seller_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('img', models.ImageField(blank=True, upload_to='photos/content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
